# frozen_string_literal: true

source "https://rubygems.org"

gem "rails_event_store", path: "../../"
gem "ruby_event_store", path: "../../../ruby_event_store"
gem "ruby_event_store-browser", path: "../../../ruby_event_store-browser"
gem "ruby_event_store-active_record", path: "../../../ruby_event_store-active_record"
gem "rails_event_store_active_record", path: "../../../ruby_event_store-active_record"
gem "aggregate_root", path: "../../../aggregate_root"

gem "rails", "~> 6.0.6"
