# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
  - ruby_event_store/profiler
includes:
  - lib
integration:
  name: rspec
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - RubyEventStore::Profiler*
