# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"

gem "ruby_event_store", path: "../.."
gem "aggregate_root", path: "../.."

gem "activesupport", "~> 7.2.2.1"

