# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"

gem "ruby_event_store", path: "../.."
gem "aggregate_root", path: "../.."
gem "rails_event_store", path: "../.."
gem "ruby_event_store-active_record", path: "../.."
gem "rails_event_store_active_record", path: "../.."
gem "ruby_event_store-browser", path: "../.."

gem "protobuf_nested_struct"
gem "google-protobuf", "~> 3.24"
gem "rails", "~> 8.0.0"
gem "zeitwerk", "~> 2.6.0"
