source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

eval_gemfile '../../support/bundler/Gemfile.shared'

gem 'protobuf_nested_struct'
gem 'google-protobuf', '~> 3.14.0'
gem 'ruby_event_store', path: '../../ruby_event_store'
