# https://github.com/mbj/mutant/blob/master/docs/configuration.md

usage: opensource
requires:
  - minitest/ruby_event_store
includes:
  - lib
integration:
  name: minitest
mutation:
  operators: full
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Minitest::RubyEventStore*
