source 'https://rubygems.org'

gem 'rails',    '~> 5.2'
gem 'pg',       '>= 0.18', '< 2.0'
gem 'puma',     '~> 3.11'
gem 'bootsnap', '>= 1.4.0', require: false


gem 'rails_event_store', '~> 2.1.0'
gem 'dres_client',       '~> 0.6.0', path: '../dres_client'
gem 'dres_rails',        '~> 0.6.0', path: '../dres_rails'
