# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
- ruby_event_store/outbox
- ruby_event_store/outbox/cli
includes:
- lib
integration: rspec
mutation_timeout: 10.0
coverage_criteria:
   timeout: true
   process_abort: true
matcher:
   subjects:
   - RubyEventStore::Outbox*
   ignore:
   - RubyEventStore::Outbox::CLI*
   - RubyEventStore::Outbox::SidekiqScheduler#call
   - RubyEventStore::Outbox::SidekiqProducer#call
   - RubyEventStore::Outbox::SidekiqProcessor#process
   - RubyEventStore::Outbox::SidekiqProcessor#after_batch
   - RubyEventStore::Outbox::Metrics.from_url
   - RubyEventStore::Outbox::FetchSpecification#initialize
   - RubyEventStore::Outbox::Consumer::Configuration
   - RubyEventStore::Outbox::Consumer#run
   - RubyEventStore::Outbox::Consumer#retrieve_batch
   - RubyEventStore::Outbox::Consumer#release_lock_for_process
   - RubyEventStore::Outbox::Consumer#refresh_lock_for_process
   - RubyEventStore::Outbox::Consumer#prepare_traps
   - RubyEventStore::Outbox::Consumer#one_loop
   - RubyEventStore::Outbox::Consumer#obtain_lock_for_process
   - RubyEventStore::Outbox::Consumer#initiate_graceful_shutdown
   - RubyEventStore::Outbox::Consumer#initialize
   - RubyEventStore::Outbox::Consumer#init
   - RubyEventStore::Outbox::Consumer#handle_split
   - RubyEventStore::Outbox::Consumer::Configuration*
   - RubyEventStore::Outbox::Consumer#get_remaining_count
   - RubyEventStore::Outbox::Repository*

