source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"
eval_gemfile "../../support/bundler/Gemfile.database"

gem "ruby_event_store", path: "../.."

gem "sidekiq", "~> 6.2"
gem "influxdb", "~> 0.8.1", require: false
gem "childprocess"
gem "rails", "7.0.4.1"
