source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

eval_gemfile File.expand_path('../../support/bundler/Gemfile.shared', __dir__)

gem 'sidekiq', '5.2.7'

gem 'ruby_event_store', path: '../../ruby_event_store'
gem 'pg', '1.2.2'
gem 'mysql2', '0.5.3'
gem 'influxdb', '~> 0.8.0', require: false
gem 'childprocess'
gem 'rails', ENV['RAILS_VERSION']

if Gem::Version.new(ENV['RAILS_VERSION']) >= Gem::Version.new('6.0.0')
  gem 'sqlite3', '1.4.2'
else
  gem 'sqlite3', '1.3.13'
end


gem 'byebug'
