# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"
gem "pg", "~> 1.5.6"
gem "mysql2", "~> 0.5.6"
gem "sqlite3", "~> 2.5.0"

gem "ruby_event_store", path: "../.."

gem "sidekiq", "~> 7.2"
gem "influxdb", "~> 0.8.1", require: false
gem "childprocess"
gem "rails", "~> 8.0.1"
