# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
  - rails_event_store
includes:
  - lib
integration:
  name: rspec
mutation:
  operators: full
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - RailsEventStore*
  ignore:
    - RailsEventStore::Client#initialize
    - RailsEventStore::JSONClient#initialize
    - RailsEventStore::AfterCommitAsyncDispatcher::AsyncRecord*
    - RailsEventStore::AfterCommitAsyncDispatcher#async_record
    - RailsEventStore::AsyncHandler.with