source 'https://rubygems.org'
gemspec name: 'ruby_event_store-rspec'

eval_gemfile '../support/bundler/Gemfile.shared'

gem 'ruby_event_store', path: '../ruby_event_store'
gem 'aggregate_root',   path: '../aggregate_root'

gem 'diff-lcs', '= 1.3.0'
