source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

eval_gemfile '../support/bundler/Gemfile.shared'

gem 'ruby_event_store', path: '../ruby_event_store'
gem 'aggregate_root', path: '../aggregate_root'

gem 'diff-lcs', '= 1.3.0'
