# https://github.com/mbj/mutant/blob/master/docs/configuration.md

usage: opensource
requires:
  - ruby_event_store/sequel
includes:
  - lib
integration:
  name: rspec
mutation:
  operators: light
  timeout: 1.0
coverage_criteria:
  timeout: true
  process_abort: true
matcher:
  subjects:
    - RubyEventStore::Sequel*
