# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"
eval_gemfile "../../support/bundler/Gemfile.database"

gem "ruby_event_store", path: "../.."

gem "activesupport", "~> 7.2.2.1"
gem "sqlite3", ">= 1.7.3"
