# frozen_string_literal: true

source "https://rubygems.org"

gem "middleman", "~> 4.4"
gem "middleman-aria_current"
gem "middleman-syntax"
gem "redcarpet"
gem "octokit"
gem "faraday"
gem "faraday-retry"
gem "webrick"
gem "haml", "< 6"
