source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-aria_current'
gem 'middleman-syntax'
gem 'middleman-livereload'
gem 'redcarpet'
gem 'slim'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw]
