# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

require 'google/protobuf'


descriptor_data = "\n\x0c\x65vents.proto\x12\x0bres_testing\"5\n\x0cOrderCreated\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ustomer_id\x18\x02 \x01(\x05\"\x0b\n\tOrderPaid\"\x14\n\x12SpanishInquisitionb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module ResTesting
  OrderCreated = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("res_testing.OrderCreated").msgclass
  OrderPaid = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("res_testing.OrderPaid").msgclass
  SpanishInquisition = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("res_testing.SpanishInquisition").msgclass
end
