source 'https://rubygems.org'
gem 'activerecord', ENV['RAILS_VERSION']
gem 'ruby_event_store', path: '../../../ruby_event_store'
gem 'rails_event_store_active_record', path: '../../../rails_event_store_active_record'
gem 'sqlite3', '1.3.13'
gem 'pg', '0.21'
gem 'mysql2', '0.4.10'