source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gemspec
gem 'pry'
gem 'rails_event_store_active_record',
    github: "RailsEventStore/rails_event_store",
    branch: "fill_ids"
gem 'ruby_event_store',
    github: "RailsEventStore/rails_event_store",
    branch: "fill_ids"
gem 'rails_event_store',
    github: "RailsEventStore/rails_event_store",
    branch: "fill_ids"