# https://github.com/mbj/mutant/blob/master/docs/configuration.md

usage: opensource
requires:
  - ruby_event_store/cli/commands
includes:
  - lib
integration:
  name: rspec
mutation:
  operators: light
  timeout: 10.0
coverage_criteria:
  timeout: true
  process_abort: true
matcher:
  subjects:
    - RubyEventStore::CLI*
  ignore:
    - RubyEventStore::CLI::VERSION
