# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"

gem "ruby_event_store", path: "../.."
gem "rails_event_store_active_record", path: "../../ruby_event_store-active_record"
gem "sqlite3", ">= 2.1"
gem "rails", "~> 8.0.0"
