source "https://rubygems.org"
gemspec name: "ruby_event_store-active_record"

eval_gemfile "../support/bundler/Gemfile.shared"
eval_gemfile "../support/bundler/Gemfile.database"

gem "ruby_event_store", path: "../ruby_event_store"

gem "childprocess"
