require_relative "lib/ruby_event_store/active_record/generators/no_rails_migration_generator"

namespace :g do
  desc "Generate migration"
  task :migration, :data_type, :migration_path do |_,args|
    data_type = args[:data_type] || raise("Specify data type (binary, json, jsonb): rake g:migration[data_type]")

    path = RubyEventStore::ActiveRecord::NoRailsMigrationGenerator
      .new
      .call(data_type, args[:migration_path])

    puts "Migration #{path} created"

    exit
  end
end