require "active_record"
require "yaml"
require_relative "lib/ruby_event_store/active_record/generators/no_rails_migration_generator"

namespace :g do
  desc "Generate migration"
  task :migration do
    data_type = ARGV[1] || raise("Specify name: rake g:migration data_type")

    RubyEventStore::ActiveRecord::NoRailsMigrationGenerator
      .new
      .call(data_type, ARGV[2])

    puts "Migration #{path} created"

    exit
  end
end