require_relative "lib/ruby_event_store/active_record/generators/migration_generator"

namespace :g do
  desc "Generate migration"
  task :migration, :data_type, :migration_path do |_,args|
    data_type = args[:data_type] || raise("Specify data type (binary, json, jsonb): rake g:migration[data_type]")

    path = RubyEventStore::ActiveRecord::MigrationGenerator
      .new
      .call(data_type, args[:migration_path] || "db/migrate")

    puts "Migration #{path} created"
  end
end