# https://github.com/mbj/mutant/blob/master/docs/configuration.md

usage: opensource
requires:
  - ruby_event_store/browser
  - ruby_event_store/browser/app
includes:
  - lib
integration:
  name: rspec
mutation:
  operators: full
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - RubyEventStore::Browser*
  ignore:
    - RubyEventStore::Browser::App#res_version
    - RubyEventStore::Browser::App.for
    - RubyEventStore::Browser::App#initialize
    - RubyEventStore::Browser::Urls#with_request
    - RubyEventStore::Browser::Urls#initialize
    - RubyEventStore::Browser::Router#initialize
