source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem 'rake',         '>= 10.0'
gem 'rspec',        '~> 3.6'
gem 'mutant-rspec', '~> 0.10.15'
gem 'mutant',       '~> 0.10.15'
gem 'mutant-license', source: 'https://oss:7AXfeZdAfCqL1PvHm2nvDJO6Zd9UW8IK@gem.mutant.dev'

gem 'ruby_event_store', path: '../ruby_event_store'
gem 'aggregate_root',   path: '../aggregate_root'
gem 'bounded_context',  path: '../bounded_context'
gem 'rack-test'
gem 'capybara', '~> 3.18'
gem 'selenium-webdriver', '~> 3.141'
gem 'json-schema'
gem 'rack'
