# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../support/bundler/Gemfile.shared"

gem "ruby_event_store", path: ".."

gem "rack-test"
gem "capybara", "~> 3.35"
gem "json-schema"
gem "rack", "~> 3.0"
gem "webrick"
gem "cuprite"
gem "rackup"
