#!/usr/bin/env ruby

begin
  require 'ruby_event_store/deprecated_read_api_rewriter'
  require 'ruby_event_store/deprecated_read_api_runner'
rescue LoadError
  warn <<-EOS

You need following gems in Gemfile in order to use this script:

  gem 'parser'
  gem 'unparser'
  gem 'astrolabe'

EOS
  exit(2)
end

RubyEventStore::DeprecatedReadAPIRunner.go(ARGV)
