# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "ruby_event_store", path: "../../ruby_event_store"
gem "ruby_event_store-active_record", path: "../../ruby_event_store-active_record"
gem "rails_event_store", path: "../../rails_event_store"
gem "aggregate_root", path: "../../aggregate_root"

gem "rspec"
gem "rack-test"
