# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"

gem "redis-client", "~> 0.21.1"
gem "sidekiq", "~> 7.0"
gem "ruby_event_store", path: "../.."
gem "rails_event_store", path: "../.."
gem "rails", "~> 7.0.7"
gem "bigdecimal"
gem "mutex_m"
