# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"

gem "sidekiq", "~> 7.2"
gem "ruby_event_store", path: "../.."
gem "rails_event_store", path: "../.."
gem "rails", "~> 8.0.0"
gem "zeitwerk", "~> 2.6.0"
