# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
- rails_event_store_active_record
includes:
- lib
integration: rspec
mutation_timeout: 10.0
coverage_criteria:
   timeout: true
   process_abort: true
matcher:
   subjects:
   - RailsEventStoreActiveRecord*
   ignore:
   -  RailsEventStoreActiveRecord::IndexViolationDetector#initialize
   -  RailsEventStoreActiveRecord::IndexViolationDetector#detect
   -  RailsEventStoreActiveRecord::IndexViolationDetector#detect_mysql
   -  RailsEventStoreActiveRecord::IndexViolationDetector#detect_postgres
   -  RailsEventStoreActiveRecord::PgLinearizedEventRepository*
   -  RailsEventStoreActiveRecord::EventRepository#update_messages
   -  RailsEventStoreActiveRecord::WithAbstractBaseClass#build_event_klass
   -  RailsEventStoreActiveRecord::WithAbstractBaseClass#build_stream_klass