source 'https://rubygems.org'
gemspec

gem 'ruby_event_store', path: '../ruby_event_store'
gem 'rails', '~> 5.2'
gem 'sqlite3', '1.3.13'
gem 'pg', '0.21'
gem 'mysql2', '0.4.10'
gem 'fakefs', '~> 0.11.2'
gem 'childprocess'

if v = ENV['RAILS_VERSION']
  gem 'rails', v
end

eval_gemfile File.expand_path('../lib/Gemfile.shared', __dir__)