source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

gem 'rake',         '>= 10.0'
gem 'rspec',        '~> 3.6'
gem 'mutant-rspec', '~> 0.10.15'
gem 'mutant',       '~> 0.10.15'
gem 'mutant-license', source: 'https://oss:7AXfeZdAfCqL1PvHm2nvDJO6Zd9UW8IK@gem.mutant.dev'

gem 'ruby_event_store', path: '../ruby_event_store'
gem 'pg', '1.2.2'
gem 'mysql2', '0.5.3'
gem 'fakefs', '~> 1.2'
gem 'childprocess'
gem 'rails', '6.0.3.4'
gem 'sqlite3', '1.4.2'