source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

eval_gemfile File.expand_path('../lib/bundler/Gemfile.shared', __dir__)

gem 'ruby_event_store', path: '../ruby_event_store'
gem 'sqlite3', '1.3.13'
gem 'pg', '0.21'
gem 'mysql2', '0.4.10'
gem 'fakefs', '~> 0.11.2'
gem 'childprocess'
gem 'rails', ENV['RAILS_VERSION']