source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

eval_gemfile File.expand_path('../support/bundler/Gemfile.shared', __dir__)

gem 'mysql2', '>= 0.5.3'
gem 'pg', '>= 1.2.2'
gem 'ruby_event_store', path: '../ruby_event_store'
gem 'sqlite3', '1.3.13'
