source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in connected_active_record.gemspec
gemspec

gem 'ruby_event_store', path: '../../ruby_event_store'
gem 'rails_event_store_active_record', path: '../../rails_event_store_active_record'
gem 'childprocess'
gem 'sqlite3', '1.4.2'