# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"

gem "ruby_event_store", path: "../../ruby_event_store"
gem "ruby_event_store-browser", path: "../../ruby_event_store-browser"
gem "rails_event_store", path: "../../rails_event_store"
gem "rails_event_store_active_record", path: "../../rails_event_store_active_record"
gem "aggregate_root", path: "../../aggregate_root"

gem "pg"
gem "childprocess"
gem "rspec-rails"
gem "capybara"
gem "timecop"
