# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"

gem "ruby_event_store", path: "../.."
gem "ruby_event_store-browser", path: "../.."
gem "rails_event_store", path: "../.."
gem "ruby_event_store-active_record", path: "../.."
gem "rails_event_store_active_record", path: "../.."
gem "aggregate_root", path: "../.."

gem "pg"
gem "childprocess"
gem "rspec-rails"
gem "capybara"
gem "timecop"
gem "zeitwerk", "~> 2.6.0"
