# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
- minitest/rails_event_store
includes:
- lib
integration: minitest
mutation_timeout: 10.0
coverage_criteria:
   timeout: true
   process_abort: true
matcher:
   subjects:
   - Minitest::RailsEventStore*
