# frozen_string_literal: true

source "https://rubygems.org"
gemspec
gem 'rails_event_store_active_record',
    github: "RailsEventStore/rails_event_store"
gem 'ruby_event_store',
    github: "RailsEventStore/rails_event_store"
gem 'rails_event_store',
    github: "RailsEventStore/rails_event_store"
gem 'pg'