# frozen_string_literal: true

source "https://rubygems.org"
gemspec

gem 'rails_event_store_active_record', path: '../../../rails_event_store_active_record'
gem 'ruby_event_store',                path: '../../../ruby_event_store'
gem 'rails_event_store',               path: '../../../rails_event_store'
gem 'pg'
gem 'childprocess'