# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
- ruby_event_store/rom
includes:
- lib
integration: rspec
mutation_timeout: 10.0
coverage_criteria:
   timeout: true
   process_abort: true
matcher:
   subjects:
   - RubyEventStore::ROM*