source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"

gem "pg", "1.3.5"
gem "mysql2", "0.5.4"
gem "sqlite3", "1.4.2"
gem "ruby_event_store", path: "../../ruby_event_store"
gem "activesupport", ">= 6.0"
