source 'https://rubygems.org'
gemspec

eval_gemfile '../../support/bundler/Gemfile.shared'

gem 'mysql2', '>= 0.5.3'
gem 'pg', '>= 1.2.2'
gem 'ruby_event_store', path: '../../ruby_event_store'
gem 'sqlite3', '1.4.2'
gem 'activesupport'