source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"
eval_gemfile "../../support/bundler/Gemfile.database"

gem "ruby_event_store", path: "../../ruby_event_store"

gem "activesupport", ">= 6.0"
