# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

eval_gemfile File.expand_path('../support/bundler/Gemfile.shared', __dir__)

gem 'rails', ENV['RAILS_VERSION']