# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

eval_gemfile '../support/bundler/Gemfile.shared'

gem 'rails', ENV['RAILS_VERSION']