GEM_VERSION = $(shell cat ../RES_VERSION)
GEM_NAME    = bounded_context
REQUIRE     = $(GEM_NAME)
IGNORE      =
SUBJECT     ?= BoundedContext*

include ../lib/install.mk
include ../lib/test.mk
include ../lib/mutant.mk
include ../lib/gem.mk
include ../lib/help.mk
