# frozen_string_literal: true

source "https://rubygems.org"
gemspec

eval_gemfile "../../support/bundler/Gemfile.shared"

gem "ruby_event_store", path: "../../ruby_event_store"

gem "webmock"
gem "closed_struct"
gem "equalizer"
