# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
  - aggregate_root
includes:
  - lib
integration:
  name: rspec
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - AggregateRoot*
  ignore:
    - AggregateRoot::DefaultApplyStrategy#event_type
