# https://github.com/mbj/mutant/blob/master/docs/configuration.md

requires:
- aggregate_root
includes:
- lib
integration: rspec
mutation_timeout: 10.0
coverage_criteria:
   timeout: true
   process_abort: true
matcher:
   subjects:
   - AggregateRoot*
   ignore:
   - AggregateRoot::DefaultApplyStrategy#event_type