# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

eval_gemfile File.expand_path('../support/bundler/Gemfile.shared', __dir__)

gem 'ruby_event_store', path: '../ruby_event_store'
gem 'protobuf_nested_struct'
gem 'google-protobuf', '~> 3.12.2', '>= 3.12.2'
gem 'activesupport', '~> 5.0'
