# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gemspec

eval_gemfile '../support/bundler/Gemfile.shared'

gem 'ruby_event_store', path: '../ruby_event_store'
gem 'activesupport', '~> 5.0'
