source 'https://rubygems.org'

gemspec

eval_gemfile '../support/bundler/Gemfile.shared'

gem 'activesupport', '6.0.3.4'
gem 'concurrent-ruby', github: 'ruby-concurrency/concurrent-ruby', ref: 'c4cbc968c55e5b983dae953095761896220c46d1'
gem 'rbs'
