source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gemspec
gem 'ruby_event_store', path: '../../../ruby_event_store'
gem 'closed_struct'
gem 'equalizer'
