source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gemspec
gem 'ruby_event_store', github: "RailsEventStore/rails_event_store"
gem 'closed_struct'
gem 'equalizer'