name: dres_client_test
on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - script
  push:
    paths: &1
    - contrib/dres_client/**
    - contrib/dres_rails/**
    - ".github/workflows/dres_client_test.yml"
    - support/**
    - "!support/bundler/**"
    - "!support/ci/**"
  pull_request:
    types:
    - opened
    - reopened
    paths: *1
jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    env:
      WORKING_DIRECTORY: contrib/dres_client
      RUBY_VERSION: "${{ matrix.ruby_version }}"
      BUNDLE_GEMFILE: "${{ matrix.bundle_gemfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby_version: ruby-3.2
          bundle_gemfile: Gemfile
        - ruby_version: ruby-3.1
          bundle_gemfile: Gemfile
        - ruby_version: ruby-3.0
          bundle_gemfile: Gemfile
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
      working-directory: "${{ env.WORKING_DIRECTORY }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ env.RUBY_VERSION }}"
        bundler-cache: true
        working-directory: "${{ env.WORKING_DIRECTORY }}"
    - run: make test
      working-directory: "${{ env.WORKING_DIRECTORY }}"