name: minitest-ruby_event_store_coverage
on:
  repository_dispatch:
    types:
      - script
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    paths:
      - "contrib/minitest-ruby_event_store/Gemfile.lock"
      - ".github/workflows/minitest-ruby_event_store_coverage.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/minitest-ruby_event_store/Gemfile.lock"
      - ".github/workflows/minitest-ruby_event_store_coverage.yml"
      - "support/**"
jobs:
  coverage:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/minitest-ruby_event_store
      BUNDLE_GEMFILE: Gemfile
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.1
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate
        working-directory: ${{ env.WORKING_DIRECTORY }}
