name: minitest-ruby_event_store_mutate
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  push:
    paths:
      - contrib/minitest-ruby_event_store/**
      - ".github/workflows/minitest-ruby_event_store_mutate.yml"
      - support/**
      - "!support/bundler/**"
      - "!support/ci/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - contrib/minitest-ruby_event_store/**
      - ".github/workflows/minitest-ruby_event_store_mutate.yml"
      - support/**
      - "!support/bundler/**"
      - "!support/ci/**"
jobs:
  mutate:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    env:
      WORKING_DIRECTORY: contrib/minitest-ruby_event_store
      RUBY_VERSION: "${{ matrix.ruby_version }}"
      BUNDLE_GEMFILE: "${{ matrix.bundle_gemfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby_version: ruby-3.2
          bundle_gemfile: Gemfile
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
      working-directory: "${{ env.WORKING_DIRECTORY }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ env.RUBY_VERSION }}"
        bundler-cache: true
        working-directory: "${{ env.WORKING_DIRECTORY }}"
    - run: make mutate-changes
      working-directory: "${{ env.WORKING_DIRECTORY }}"