name: minitest-ruby_event_store_coverage
on:
  repository_dispatch:
    types:
      - script
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    paths:
      - "contrib/minitest-ruby_event_store/Gemfile.lock"
      - ".github/workflows/minitest-ruby_event_store_coverage.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/minitest-ruby_event_store/Gemfile.lock"
      - ".github/workflows/minitest-ruby_event_store_coverage.yml"
      - "support/**"
jobs:
  coverage:
    runs-on: ${{ matrix.os }}
    env:
      WORKING_DIRECTORY: contrib/minitest-ruby_event_store
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
      MUTANT_JOBS: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.1
            gemfile: Gemfile
            os: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate
        working-directory: ${{ env.WORKING_DIRECTORY }}
