name: rails_event_store_coverage
on:
  repository_dispatch:
    types:
      - script
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    paths:
      - "rails_event_store/Gemfile.lock"
      - ".github/workflows/rails_event_store_coverage.yml"
      - "support/**"
  pull_request:
    types: [ opened, reopened ]
    paths:
      - "rails_event_store/Gemfile.lock"
      - ".github/workflows/rails_event_store_coverage.yml"
      - "support/**"
jobs:
  coverage:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    env:
      BUNDLE_GEMFILE: Gemfile
      WORKING_DIRECTORY: rails_event_store
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-2.7
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate
        working-directory: ${{ env.WORKING_DIRECTORY }}
