name: rails_event_store-rspec
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      GEM_NAME: rails_event_store-rspec
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
          - ruby: ruby-2.6
            gemfile: Gemfile
          - ruby: ruby-2.5
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make test
        working-directory: ${{ env.GEM_NAME }}

  mutate:
    runs-on: ubuntu-20.04
    env:
      GEM_NAME: rails_event_store-rspec
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-2.7
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.GEM_NAME }}
      - run: make mutate-changes
        working-directory: ${{ env.GEM_NAME }}
