name: ruby_event_store-protobuf
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  push:
    paths:
      - "contrib/ruby_event_store-protobuf/**"
      - ".github/workflows/ruby_event_store-protobuf.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-protobuf/**"
      - ".github/workflows/ruby_event_store-protobuf.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-protobuf
      RUBY_VERSION: "${{ matrix.ruby_version }}"
      BUNDLE_GEMFILE: "${{ matrix.bundle_gemfile }}"
      DATABASE_URL: "${{ matrix.database_url }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby_version: ruby-3.1
            bundle_gemfile: Gemfile
            database_url: sqlite3:db.sqlite3
          - ruby_version: ruby-3.0
            bundle_gemfile: Gemfile
            database_url: sqlite3:db.sqlite3
          - ruby_version: ruby-2.7
            bundle_gemfile: Gemfile
            database_url: sqlite3:db.sqlite3
          - ruby_version: ruby-3.1
            bundle_gemfile: Gemfile.rails_6_1
            database_url: sqlite3:db.sqlite3
          - ruby_version: ruby-3.0
            bundle_gemfile: Gemfile.rails_6_1
            database_url: sqlite3:db.sqlite3
          - ruby_version: ruby-2.7
            bundle_gemfile: Gemfile.rails_6_1
            database_url: sqlite3:db.sqlite3
          - ruby_version: ruby-2.7
            bundle_gemfile: Gemfile.rails_6_0
            database_url: sqlite3:db.sqlite3
    steps:
      - uses: actions/checkout@v3
      - run: test -e ${{ matrix.bundle_gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-protobuf
      BUNDLE_GEMFILE: Gemfile
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.1
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate-changes
        working-directory: ${{ env.WORKING_DIRECTORY }}
