name: ruby_event_store-rom_mutate
on:
  workflow_dispatch:
  repository_dispatch:
    types:
    - script
  push:
    paths:
    - contrib/ruby_event_store-rom/**
    - ".github/workflows/ruby_event_store-rom_mutate.yml"
    - support/**
    - "!support/bundler/**"
    - "!support/ci/**"
  pull_request:
    types:
    - opened
    - reopened
    paths:
    - contrib/ruby_event_store-rom/**
    - ".github/workflows/ruby_event_store-rom_mutate.yml"
    - support/**
    - "!support/bundler/**"
    - "!support/ci/**"
jobs:
  mutate:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-rom
      RUBY_VERSION: "${{ matrix.ruby_version }}"
      BUNDLE_GEMFILE: "${{ matrix.bundle_gemfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby_version: ruby-3.2
          bundle_gemfile: Gemfile
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
      working-directory: "${{ env.WORKING_DIRECTORY }}"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ env.RUBY_VERSION }}"
        bundler-cache: true
        working-directory: "${{ env.WORKING_DIRECTORY }}"
    - run: make mutate-changes
      working-directory: "${{ env.WORKING_DIRECTORY }}"