name: ruby_event_store-sidekiq_scheduler
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  push:
    paths:
      - "contrib/ruby_event_store-sidekiq_scheduler/**"
      - ".github/workflows/ruby_event_store-sidekiq_scheduler.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-sidekiq_scheduler/**"
      - ".github/workflows/ruby_event_store-sidekiq_scheduler.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-sidekiq_scheduler
      RUBY_VERSION: "${{ matrix.ruby_version }}"
      BUNDLE_GEMFILE: "${{ matrix.bundle_gemfile }}"
      REDIS_URL: "${{ matrix.redis_url }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby_version: ruby-3.2
            bundle_gemfile: Gemfile
            redis_url: redis://localhost:6379/0
          - ruby_version: ruby-3.1
            bundle_gemfile: Gemfile
            redis_url: redis://localhost:6379/0
          - ruby_version: ruby-3.0
            bundle_gemfile: Gemfile
            redis_url: redis://localhost:6379/0
          - ruby_version: ruby-3.2
            bundle_gemfile: Gemfile.sidekiq_6_5
            redis_url: redis://localhost:6379/0
          - ruby_version: ruby-3.2
            bundle_gemfile: Gemfile.sidekiq_5_2
            redis_url: redis://localhost:6379/0
          - ruby_version: ruby-3.0
            bundle_gemfile: Gemfile.sidekiq_6_5
          - ruby_version: ruby-3.0
            bundle_gemfile: Gemfile.sidekiq_5_2
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: railseventstore
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: test -e ${{ matrix.bundle_gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make test" -E"
            with import <nixpkgs> { };
            mkShell {
              inputsFrom = [
                (import ../../support/nix/redis.nix)
              ];
            }
          "
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-sidekiq_scheduler
      BUNDLE_GEMFILE: Gemfile
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: railseventstore
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.1
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make mutate-changes" -E"
            with import <nixpkgs> { };
            mkShell {
              inputsFrom = [
                (import ../../support/nix/redis.nix)
              ];
            }
          "
        working-directory: ${{ env.WORKING_DIRECTORY }}
