name: ruby_event_store-active_record_coverage
on:
  repository_dispatch:
    types:
      - script
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
  push:
    paths:
      - "ruby_event_store-active_record/Gemfile.lock"
      - ".github/workflows/ruby_event_store-active_record_coverage.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "ruby_event_store-active_record/Gemfile.lock"
      - ".github/workflows/ruby_event_store-active_record_coverage.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
jobs:
  coverage:
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    env:
      WORKING_DIRECTORY: ruby_event_store-active_record
      RUBY_VERSION: "${{ matrix.ruby_version }}"
      BUNDLE_GEMFILE: "${{ matrix.bundle_gemfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby_version: ruby-3.2
            bundle_gemfile: Gemfile
    steps:
      - uses: actions/checkout@v3
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.1
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate
        working-directory: ${{ env.WORKING_DIRECTORY }}
