name: ruby_event_store-sidekiq_scheduler
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  push:
    paths:
      - "contrib/ruby_event_store-sidekiq_scheduler/**"
      - ".github/workflows/ruby_event_store-sidekiq_scheduler.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-sidekiq_scheduler/**"
      - ".github/workflows/ruby_event_store-sidekiq_scheduler.yml"
      - "support/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-sidekiq_scheduler
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      REDIS_URL: redis://localhost:6379/0
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.1
            gemfile: Gemfile
          - ruby: ruby-3.1
            gemfile: Gemfile.sidekiq_6
          - ruby: ruby-3.1
            gemfile: Gemfile.sidekiq_5
          - ruby: ruby-3.0
            gemfile: Gemfile
          - ruby: ruby-3.0
            gemfile: Gemfile.sidekiq_6
          - ruby: ruby-3.0
            gemfile: Gemfile.sidekiq_5
          - ruby: ruby-2.7
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: railseventstore
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make test" -E"
            with import <nixpkgs> { };
            mkShell {
              inputsFrom = [
                (import ../../support/nix/redis.nix)
              ];
            }
          "
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-sidekiq_scheduler
      BUNDLE_GEMFILE: Gemfile
      REDIS_URL: redis://localhost:6379/0
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v11
        with:
          name: railseventstore
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.1
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: |
          nix-shell --run "make mutate-changes" -E"
            with import <nixpkgs> { };
            mkShell {
              inputsFrom = [
                (import ../../support/nix/redis.nix)
              ];
            }
          "
        working-directory: ${{ env.WORKING_DIRECTORY }}
