name: ruby_event_store-protobuf
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  push:
    paths:
      - "contrib/ruby_event_store-protobuf/**"
      - ".github/workflows/ruby_event_store-protobuf.yml"
      - "support/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "contrib/ruby_event_store-protobuf/**"
      - ".github/workflows/ruby_event_store-protobuf.yml"
      - "support/**"
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-protobuf
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      DATABASE_URL: ${{ matrix.database }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.1
            gemfile: Gemfile
            database: sqlite3:db.sqlite3
          - ruby: ruby-3.1
            gemfile: Gemfile.rails_6_1
            database: sqlite3:db.sqlite3
          - ruby: ruby-3.0
            gemfile: Gemfile
            database: sqlite3:db.sqlite3
          - ruby: ruby-3.0
            gemfile: Gemfile.rails_6_1
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.7
            gemfile: Gemfile.rails_6_1
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.7
            gemfile: Gemfile
            database: sqlite3:db.sqlite3
          - ruby: ruby-2.7
            gemfile: Gemfile.rails_6_0
            database: sqlite3:db.sqlite3
    steps:
      - uses: actions/checkout@v3
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: contrib/ruby_event_store-protobuf
      BUNDLE_GEMFILE: Gemfile
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.1
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate-changes
        working-directory: ${{ env.WORKING_DIRECTORY }}
