name: ruby_event_store
on:
  repository_dispatch:
    types:
      - script
  workflow_dispatch:
  push:
    paths:
      - "aggregate_root/**"
      - "rails_event_store/**"
      - "ruby_event_store/**"
      - "ruby_event_store-active_record/**"
      - "ruby_event_store-browser/**"
      - "ruby_event_store-rspec/**"
      - ".github/workflows/ruby_event_store.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
  pull_request:
    types: [opened, reopened]
    paths:
      - "aggregate_root/**"
      - "rails_event_store/**"
      - "ruby_event_store/**"
      - "ruby_event_store-active_record/**"
      - "ruby_event_store-browser/**"
      - "ruby_event_store-rspec/**"
      - ".github/workflows/ruby_event_store.yml"
      - "support/**"
      - "!support/bundler/**"
      - "!support/ci/**"
defaults:
  run:
    working-directory: ruby_event_store
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: ruby_event_store
      RUBY_VERSION: "${{ matrix.ruby_version }}"
      BUNDLE_GEMFILE: "${{ matrix.bundle_gemfile }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby_version: ruby-3.2
            bundle_gemfile: Gemfile
          - ruby_version: ruby-3.1
            bundle_gemfile: Gemfile
          - ruby_version: ruby-3.0
            bundle_gemfile: Gemfile
          - ruby_version: truffleruby
            bundle_gemfile: Gemfile
    steps:
      - uses: actions/checkout@v3
      - run: test -e ${{ matrix.bundle_gemfile }}.lock
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - run: make test

  mutate:
    runs-on: ubuntu-20.04
    env:
      WORKING_DIRECTORY: ruby_event_store
      BUNDLE_GEMFILE: Gemfile
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: test -e ${{ env.BUNDLE_GEMFILE }}.lock
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.2
          bundler-cache: true
      - run: make mutate-changes
